### ISSUE TITLE
pdf embed/link is not uniform

### ISSUE THREAD

**Issue by BjarneVdv** [dwengovzw/Learning-Object-Repository#12]
Making a link to a pdf file no longer requires `@pdf` to link. Adding `@pdf` to a link will make it not work.

Embedding a pdf file does still require `@pdf`. **Not** adding `@pdf` will make it not work.

eg.
*without `@pdf`
`[link](folder/filename.pdf "")` **works**
`![](folder/filename.pdf "")` **doesn't work** and makes changes not compile

*with `@pdf`*
`[link](@pdf/folder/filename.pdf "")` **doesn't work**
`![](@pdf/folder/filename.pdf "")` **does work**

So required features are available, just a bit weird that one requires the `@pdf` while the other doesn't.

**Comment by pdf** [comment]
Sometimes I hate my username....

**Comment by zimcke** [comment]
This was explicitely designed as mentioned. An external pdf link is indeed just a link (like any other URL) and doesn't require the `@pdf` tag. However, a pdf file that needs to be embedded requires the `@pdf` tag to make sure it will be passed to the pdf processor. The same logic applies to other kinds of recourses that can be referred to as a link and as an embedded object.

**Comment by tomneutens** [comment]
Ideally, local pdf documents should be added as a learning object and added in markdown using the @ learning-object syntax.
